const PLAN = [
  {id:'upper-a',day:'Day 1',name:'Upper Body A',note:'Controlled reps. Stop each set with 2–3 good reps still available.',exercises:[
    ['Machine Chest Press',3,'8–12','Keep shoulder blades supported.'],['Lat Pulldown',3,'8–12','Pull toward upper chest; avoid leaning back.'],['Seated Cable Row',3,'8–12','Pause briefly with elbows back.'],['Machine Shoulder Press',2,'8–12','Use a pain-free shoulder range.'],['Dumbbell Lateral Raise',2,'12–15','Use light weights and soft elbows.'],['Cable Triceps Pressdown',2,'10–15','Keep elbows close to your sides.'],['Dumbbell Hammer Curl',2,'10–15','Keep wrists neutral.']]},
  {id:'lower-a',day:'Day 2',name:'Lower Body A',note:'Hip-friendly session: use a comfortable depth and controlled tempo.',exercises:[
    ['Goblet Squat to Bench',3,'8–12','Tap the bench; use the depth your hips tolerate.'],['Seated Leg Curl',3,'10–15','Control both directions.'],['Leg Extension',2,'10–15','Smooth reps; do not lock knees hard.'],['Glute Kickback Machine',2,'10–15 / side','Keep your pelvis steady.'],['Calf Raise',3,'10–15','Pause at the top and stretch gently.'],['Pallof Press',2,'10–12 / side','Resist rotation; brace gently.']]},
  {id:'upper-b',day:'Day 3',name:'Upper Body B',note:'A second upper-body angle with steady, repeatable technique.',exercises:[
    ['Incline Dumbbell Press',3,'8–12','Use a low incline and controlled lowering.'],['Chest-Supported Row',3,'8–12','Keep chest supported throughout.'],['Neutral-Grip Lat Pulldown',3,'8–12','Drive elbows toward your ribs.'],['Pec Deck',2,'10–15','Use a comfortable shoulder stretch.'],['Rear Delt Fly',2,'12–15','Lead with elbows; keep weight light.'],['Machine or Cable Curl',2,'10–15','Avoid swinging.'],['Overhead Cable Triceps Extension',2,'10–15','Keep ribs down and elbows steady.']]},
  {id:'lower-b',day:'Day 4',name:'Lower Body B',note:'Use support for balance. Skip or shorten any movement that irritates the hips.',exercises:[
    ['Supported Reverse Lunge',3,'8–10 / side','Hold a stable support; take a comfortable step.'],['Seated Leg Curl',3,'10–15','Control the return.'],['Leg Extension',2,'10–15','Use a pain-free range.'],['Hip Abductor Machine',2,'12–15','Use a limited, comfortable range.'],['Calf Raise',3,'10–15','Use full comfortable ankle motion.'],['Machine Crunch or Dead Bug',2,'10–15','Choose the version that feels best.']]}
].map(w=>({...w,exercises:w.exercises.map((e,i)=>({id:`${w.id}-${i}`,name:e[0],sets:e[1],reps:e[2],tip:e[3]}))}));

const KEY='bigEWorkoutTrackerV1';
const defaultState={history:[],draft:null,settings:{restSeconds:90}};
let state=loadState(), sessionTimer=null, restTimer=null, startedAt=null, deferredInstall=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='homeView')renderHome();if(id==='historyView')renderHistory()}
function thisWeekCount(){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);return state.history.filter(h=>new Date(h.completedAt)>=start).length}
function nextWorkout(){const count=thisWeekCount();return PLAN[Math.min(count,3)]}
function renderHome(){const complete=thisWeekCount();$('#weekProgress').textContent=`${Math.min(complete,4)} of 4 complete`;$('#startNextButton').textContent=complete>=4?'Start an extra workout':`Start ${nextWorkout().name}`;$('#workoutCards').innerHTML=PLAN.map((w,i)=>`<article class="workout-card"><div class="day-badge">${i+1}</div><div><h3>${w.name}</h3><p>${w.exercises.length} exercises · ${w.exercises.reduce((n,e)=>n+e.sets,0)} sets</p></div>${i<complete?'<span class="complete-badge">✓</span>':`<button class="start-button" data-start="${w.id}">Start</button>`}</article>`).join('');$$('[data-start]').forEach(b=>b.onclick=()=>startWorkout(b.dataset.start))}
function createDraft(workout){return {workoutId:workout.id,startedAt:new Date().toISOString(),notes:'',sets:Object.fromEntries(workout.exercises.map(e=>[e.id,Array.from({length:e.sets},()=>({weight:'',reps:'',done:false}))]))}}
function startWorkout(id){const workout=PLAN.find(w=>w.id===id);if(!workout)return;state.draft=createDraft(workout);saveState();openSession()}
function openSession(){if(!state.draft)return;const workout=PLAN.find(w=>w.id===state.draft.workoutId);startedAt=new Date(state.draft.startedAt);$('#sessionLabel').textContent=workout.day;$('#sessionTitle').textContent=workout.name;$('#sessionNote').textContent=workout.note;$('#workoutNotes').value=state.draft.notes||'';$('#exerciseList').innerHTML=workout.exercises.map(e=>`<article class="exercise-card"><div class="exercise-top"><h3>${e.name}</h3><span class="exercise-prescription">${e.sets} × ${e.reps}</span></div><p class="exercise-tip">${e.tip}</p>${state.draft.sets[e.id].map((s,i)=>`<div class="set-row"><span class="set-number">${i+1}</span><div class="field"><label>Weight (lb)</label><input inputmode="decimal" type="number" min="0" step="2.5" data-ex="${e.id}" data-set="${i}" data-field="weight" value="${s.weight}"></div><div class="field"><label>Reps</label><input inputmode="numeric" type="number" min="0" data-ex="${e.id}" data-set="${i}" data-field="reps" value="${s.reps}"></div><button class="set-check ${s.done?'done':''}" data-check="${e.id}" data-set="${i}" aria-label="Complete set">✓</button></div>`).join('')}</article>`).join('');showView('sessionView');bindSession();clearInterval(sessionTimer);sessionTimer=setInterval(updateSessionClock,1000);updateSessionClock()}
function bindSession(){$('#workoutNotes').oninput=e=>{state.draft.notes=e.target.value;saveState()};$$('#exerciseList input').forEach(i=>i.oninput=()=>{state.draft.sets[i.dataset.ex][+i.dataset.set][i.dataset.field]=i.value;saveState()});$$('[data-check]').forEach(b=>b.onclick=()=>{const s=state.draft.sets[b.dataset.check][+b.dataset.set];s.done=!s.done;b.classList.toggle('done',s.done);saveState();if(s.done)startRest()})}
function updateSessionClock(){const sec=Math.max(0,Math.floor((Date.now()-startedAt)/1000));$('#sessionDuration').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startRest(){let remaining=Number(state.settings.restSeconds)||90;$('#restOverlay').hidden=false;const draw=()=>$('#restCountdown').textContent=remaining;draw();clearInterval(restTimer);restTimer=setInterval(()=>{remaining--;draw();if(remaining<=0){skipRest();toast('Rest complete — next set!');navigator.vibrate?.([150,80,150])}},1000);$('#addTimeButton').onclick=()=>{remaining+=30;draw()}}
function skipRest(){clearInterval(restTimer);$('#restOverlay').hidden=true}
function finishWorkout(){if(!state.draft)return;const workout=PLAN.find(w=>w.id===state.draft.workoutId),sets=Object.values(state.draft.sets).flat(),completed=sets.filter(s=>s.done).length;if(!completed&&!confirm('No sets are marked complete. Finish anyway?'))return;state.history.unshift({...state.draft,name:workout.name,completedAt:new Date().toISOString(),durationMinutes:Math.max(1,Math.round((Date.now()-startedAt)/60000)),completedSets:completed,totalSets:sets.length});state.draft=null;saveState();clearInterval(sessionTimer);showView('historyView');toast('Workout saved')}
function renderHistory(){const total=state.history.length,sets=state.history.reduce((n,h)=>n+h.completedSets,0),minutes=state.history.reduce((n,h)=>n+h.durationMinutes,0);$('#historySummary').innerHTML=`<div class="stat-card"><strong>${total}</strong><span>Workouts</span></div><div class="stat-card"><strong>${sets}</strong><span>Sets</span></div><div class="stat-card"><strong>${minutes}</strong><span>Minutes</span></div>`;$('#historyList').innerHTML=total?state.history.map(h=>`<article class="history-card"><div><h3>${h.name}</h3><p>${new Date(h.completedAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} · ${h.durationMinutes} min</p>${h.notes?`<p class="history-note">${escapeHtml(h.notes)}</p>`:''}</div><strong>${h.completedSets}/${h.totalSets} sets</strong></article>`).join(''):'<div class="empty-state"><h3>No workouts yet</h3><p>Complete your first session and it will appear here.</p></div>'}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`big-e-workouts-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importData(file){try{const incoming=JSON.parse(await file.text());if(!incoming||!Array.isArray(incoming.history)||!incoming.settings)throw new Error('Invalid backup');if(!confirm(`Restore ${incoming.history.length} saved workout(s)? This replaces data currently on this phone.`))return;state={...defaultState,...incoming,draft:null};saveState();$('#restSeconds').value=state.settings.restSeconds||90;renderHome();toast('Workout data restored')}catch{alert('That file is not a valid Big E Gym Tracker backup.')}}

$$('.nav-button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#startNextButton').onclick=()=>startWorkout(nextWorkout().id);$('#backButton').onclick=()=>{clearInterval(sessionTimer);showView('homeView')};$('#finishWorkoutButton').onclick=finishWorkout;$('#skipRestButton').onclick=skipRest;$('#restSeconds').value=state.settings.restSeconds;$('#restSeconds').onchange=e=>{state.settings.restSeconds=Math.max(15,Math.min(300,+e.target.value||90));e.target.value=state.settings.restSeconds;saveState()};$('#exportButton').onclick=exportData;$('#importButton').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};$('#resetButton').onclick=()=>{if(confirm('Delete all workout history and settings? This cannot be undone.')){localStorage.removeItem(KEY);state=structuredClone(defaultState);$('#restSeconds').value=90;renderHome();toast('Workout data reset')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installButton').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
renderHome();if(state.draft&&confirm('Continue your unfinished workout?'))openSession();
