const PLAN = [
  {id:'chest-shoulders',day:'Day 1',name:'Chest & Triceps',note:'Controlled reps. Stop each set with 2–3 good reps still available.',exercises:[
    ['Supine Chest Press',3,'8–12','Keep shoulder blades supported.'],['Incline Dumbbell Bench Press',3,'8–12','Use a comfortable incline.'],['Flat Dumbbell Bench Press',3,'8–12','Lower the weights with control.'],['Supine Chest Press',3,'8–12','Keep shoulder blades supported.'],['Pec Deck / Chest Fly Machine',3,'10–15','Use a comfortable shoulder stretch.'],['Seated Machine Shoulder Press',3,'8–12','Use a pain-free shoulder range.'],['Dumbbell Lateral Raise',3,'10–15','Use light weights and soft elbows.'],['Cable Triceps Pushdown',3,'10–15','Keep elbows close to your sides.'],['Overhead Cable Triceps Extension',3,'10–15','Keep ribs down and elbows steady.'],['Assisted Dip Machine (Optional)',3,'8–12','Use assistance that allows controlled reps.']]},
  {id:'back-biceps',day:'Day 2',name:'Back & Biceps',note:'Begin with a 2-mile treadmill walk, then use steady, controlled pulling movements.',exercises:[
    ['2-Mile Treadmill Warmup Walk',1,'2 miles','Use a comfortable walking pace.'],['Seated Dual Pulley Cable Row',3,'8–12','Pause briefly with elbows back.'],['Dumbbell Rows',3,'8–12 / side','Keep the torso stable.'],['Hammer Strength Front Pulldown',3,'8–12','Pull with the back and avoid swinging.'],['Lat Pulldown',3,'8–12','Pull toward the upper chest.'],['Alternating Dumbbell Curl',3,'10–15 / side','Keep elbows close to your body.'],['Alternating Dumbbell Hammer Curl',3,'10–15 / side','Keep wrists neutral.'],['Barbell Curl',3,'8–12','Avoid leaning or swinging.'],['Cable Curl (Optional)',3,'10–15','Use constant tension and controlled reps.']]},
  {id:'legs-shoulders',day:'Day 3',name:'Legs & Shoulders',note:'Use a comfortable, pain-free range and support for balance when needed.',exercises:[
    ['Leg Press',3,'8–12','Use a comfortable, pain-free range.'],['Dumbbell Goblet Squat',3,'8–12','Choose the depth your hips tolerate.'],['Supported Dumbbell Forward Lunge',3,'8–10 / side','Hold stable support and step comfortably.'],['Seated Leg Curl',3,'10–15','Control both directions.'],['Leg Extension',3,'10–15','Use smooth reps without locking hard.'],['Seated Calf Raise or Leg-Press Calf Raise',3,'10–15','Pause at the top.'],['Seated Machine Shoulder Press',3,'8–12','Use a pain-free shoulder range.'],['Dumbbell Lateral Raise',3,'10–15','Keep elbows soft.'],['Bent-Over Lateral Raise',3,'10–15','Use light weights and control.'],['Front Plate or Dumbbell Raise',3,'10–15','Lift only to shoulder height.']]},
  {id:'full-body',day:'Day 4',name:'Full Body Workout',note:'Use support when needed. Skip or shorten any movement that irritates the hips.',exercises:[
    ['Machine Chest Press',3,'8–12','Keep shoulder blades supported.'],['Neutral-Grip Lat Pulldown',3,'8–12','Drive elbows toward your ribs.'],['Seated Row Machine',3,'8–12','Pause briefly with elbows back.'],['Dumbbell Romanian Deadlift',3,'8–12','Perform only if hip-friendly.'],['Low Step-Up or Supported Stationary Lunge',3,'8–10 / side','Use support and a comfortable range.'],['Seated Dumbbell Shoulder Press',3,'8–12','Keep ribs down.'],['Dumbbell Lateral Raise',3,'10–15','Use light, controlled reps.'],['Rope Triceps Pushdown',3,'10–15','Keep elbows steady.'],['Dumbbell Hammer Curl',3,'10–15','Keep wrists neutral.'],['Cable Wood Chop',3,'10–12 / side','Rotate under control.']]}
].map(w=>({...w,exercises:w.exercises.map((e,i)=>({id:`${w.id}-${i}`,name:e[0],sets:e[1],reps:e[2],tip:e[3]}))}));

const KEY='bigEWorkoutTrackerV1';
const defaultState={history:[],draft:null,settings:{restSeconds:90}};
let state=loadState(), sessionTimer=null, restTimer=null, startedAt=null, deferredInstall=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='homeView')renderHome();if(id==='historyView')renderHistory()}
function thisWeekCount(){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);return state.history.filter(h=>new Date(h.completedAt)>=start).length}
function nextWorkout(){const count=thisWeekCount();return PLAN[Math.min(count,3)]}
function renderHome(){const complete=thisWeekCount();$('#weekProgress').textContent=`${Math.min(complete,4)} of 4 complete`;$('#startNextButton').textContent=complete>=4?'Start an extra workout':`Start ${nextWorkout().name}`;$('#workoutCards').innerHTML=PLAN.map((w,i)=>`<article class="workout-card"><div class="day-badge">${i+1}</div><div><h3>${w.name}</h3><p>${w.exercises.length} exercises · ${w.exercises.reduce((n,e)=>n+e.sets,0)} sets</p></div>${i<complete?'<span class="complete-badge">✓</span>':`<button class="start-button" data-start="${w.id}">Start</button>`}</article>`).join('');$$('[data-start]').forEach(b=>b.onclick=()=>startWorkout(b.dataset.start))}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function createDraft(workout){return {workoutId:workout.id,startedAt:new Date().toISOString(),workoutDate:localDate(),notes:'',exerciseNotes:Object.fromEntries(workout.exercises.map(e=>[e.id,''])),sets:Object.fromEntries(workout.exercises.map(e=>[e.id,Array.from({length:e.sets},()=>({weight:'',reps:'',rpe:'',hip:'',done:false}))]))}}
function startWorkout(id){const workout=PLAN.find(w=>w.id===id);if(!workout)return;state.draft=createDraft(workout);saveState();openSession()}
function openSession(){if(!state.draft)return;const workout=PLAN.find(w=>w.id===state.draft.workoutId);if(!workout){state.draft=null;saveState();return showView('homeView')}startedAt=new Date(state.draft.startedAt);state.draft.workoutDate=state.draft.workoutDate||localDate();state.draft.exerciseNotes=state.draft.exerciseNotes||{};$('#sessionLabel').textContent=workout.day;$('#sessionTitle').textContent=workout.name;$('#sessionNote').textContent=workout.note;$('#workoutDate').value=state.draft.workoutDate;$('#workoutNotes').value=state.draft.notes||'';$('#exerciseList').innerHTML=workout.exercises.map(e=>`<article class="exercise-card"><div class="exercise-top"><h3>${e.name}</h3><span class="exercise-prescription">${e.sets} × ${e.reps}</span></div><p class="exercise-tip">${e.tip}</p>${state.draft.sets[e.id].map((s,i)=>`<div class="set-row"><span class="set-number">${i+1}</span><div class="field"><label>Weight (lb)</label><input inputmode="decimal" type="number" min="0" step="2.5" data-ex="${e.id}" data-set="${i}" data-field="weight" value="${s.weight||''}"></div><div class="field"><label>Reps</label><input inputmode="numeric" type="number" min="0" data-ex="${e.id}" data-set="${i}" data-field="reps" value="${s.reps||''}"></div><div class="field field-rpe"><label>RPE (1–10)</label><input inputmode="numeric" type="number" min="1" max="10" data-ex="${e.id}" data-set="${i}" data-field="rpe" value="${s.rpe||''}"></div><div class="field field-hip"><label>Hip (0–10)</label><input inputmode="numeric" type="number" min="0" max="10" data-ex="${e.id}" data-set="${i}" data-field="hip" value="${s.hip||''}"></div><button class="set-check ${s.done?'done':''}" data-check="${e.id}" data-set="${i}" aria-label="Complete set">✓</button></div>`).join('')}<div class="exercise-notes"><label>Exercise notes</label><textarea rows="2" data-note="${e.id}" placeholder="Form, machine setup, discomfort, or adjustment…">${escapeHtml(state.draft.exerciseNotes[e.id]||'')}</textarea></div></article>`).join('');showView('sessionView');bindSession();clearInterval(sessionTimer);sessionTimer=setInterval(updateSessionClock,1000);updateSessionClock()}
function bindSession(){$('#workoutDate').onchange=e=>{state.draft.workoutDate=e.target.value;saveState()};$('#workoutNotes').oninput=e=>{state.draft.notes=e.target.value;saveState()};$$('#exerciseList input').forEach(i=>i.oninput=()=>{state.draft.sets[i.dataset.ex][+i.dataset.set][i.dataset.field]=i.value;saveState()});$$('[data-note]').forEach(n=>n.oninput=()=>{state.draft.exerciseNotes[n.dataset.note]=n.value;saveState()});$$('[data-check]').forEach(b=>b.onclick=()=>{const s=state.draft.sets[b.dataset.check][+b.dataset.set];s.done=!s.done;b.classList.toggle('done',s.done);saveState();if(s.done)startRest()})}
function updateSessionClock(){const sec=Math.max(0,Math.floor((Date.now()-startedAt)/1000));$('#sessionDuration').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startRest(){let remaining=Number(state.settings.restSeconds)||90;$('#restOverlay').hidden=false;const draw=()=>$('#restCountdown').textContent=remaining;draw();clearInterval(restTimer);restTimer=setInterval(()=>{remaining--;draw();if(remaining<=0){skipRest();toast('Rest complete — next set!');navigator.vibrate?.([150,80,150])}},1000);$('#addTimeButton').onclick=()=>{remaining+=30;draw()}}
function skipRest(){clearInterval(restTimer);$('#restOverlay').hidden=true}
function finishWorkout(){if(!state.draft)return;const workout=PLAN.find(w=>w.id===state.draft.workoutId),sets=Object.values(state.draft.sets).flat(),completed=sets.filter(s=>s.done).length;if(!completed&&!confirm('No sets are marked complete. Finish anyway?'))return;state.history.unshift({...state.draft,name:workout.name,completedAt:new Date().toISOString(),durationMinutes:Math.max(1,Math.round((Date.now()-startedAt)/60000)),completedSets:completed,totalSets:sets.length});state.draft=null;saveState();clearInterval(sessionTimer);showView('historyView');toast('Workout saved')}
function renderHistory(){const total=state.history.length,sets=state.history.reduce((n,h)=>n+h.completedSets,0),minutes=state.history.reduce((n,h)=>n+h.durationMinutes,0);$('#historySummary').innerHTML=`<div class="stat-card"><strong>${total}</strong><span>Workouts</span></div><div class="stat-card"><strong>${sets}</strong><span>Sets</span></div><div class="stat-card"><strong>${minutes}</strong><span>Minutes</span></div>`;$('#historyList').innerHTML=total?state.history.map(h=>`<article class="history-card"><div><h3>${h.name}</h3><p>${new Date(`${h.workoutDate||h.completedAt.slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} · ${h.durationMinutes} min</p>${h.notes?`<p class="history-note">${escapeHtml(h.notes)}</p>`:''}</div><strong>${h.completedSets}/${h.totalSets} sets</strong></article>`).join(''):'<div class="empty-state"><h3>No workouts yet</h3><p>Complete your first session and it will appear here.</p></div>'}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`eric-jenkins-workouts-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importData(file){try{const incoming=JSON.parse(await file.text());if(!incoming||!Array.isArray(incoming.history)||!incoming.settings)throw new Error('Invalid backup');if(!confirm(`Restore ${incoming.history.length} saved workout(s)? This replaces data currently on this phone.`))return;state={...defaultState,...incoming,draft:null};saveState();$('#restSeconds').value=state.settings.restSeconds||90;renderHome();toast('Workout data restored')}catch{alert('That file is not a valid Eric Jenkins Workout Log backup.')}}

$$('.nav-button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#startNextButton').onclick=()=>startWorkout(nextWorkout().id);$('#backButton').onclick=()=>{clearInterval(sessionTimer);showView('homeView')};$('#finishWorkoutButton').onclick=finishWorkout;$('#skipRestButton').onclick=skipRest;$('#restSeconds').value=state.settings.restSeconds;$('#restSeconds').onchange=e=>{state.settings.restSeconds=Math.max(15,Math.min(300,+e.target.value||90));e.target.value=state.settings.restSeconds;saveState()};$('#exportButton').onclick=exportData;$('#importButton').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};$('#resetButton').onclick=()=>{if(confirm('Delete all workout history and settings? This cannot be undone.')){localStorage.removeItem(KEY);state=structuredClone(defaultState);$('#restSeconds').value=90;renderHome();toast('Workout data reset')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installButton').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
renderHome();if(state.draft&&confirm('Continue your unfinished workout?'))openSession();
